### ISSUE TITLE
Disk health check

### ISSUE THREAD

**Issue by ldrrp** [SiloCityLabs/docker-nas#32]
## Problem

Currently there are no checks for disk health. This is a problem if we want to ensure data is not lost.

## Solution

On a cron check for the health of the disks and if any are unhealthy we should notify the user and log the issue.

 - We must scan for all physical drives ignoring raid groups and partitions.
 - We should add those drives to a list of disks to configure in config.yml.
 - Include config.yml settings disk checks with a custom golang struct.
 - We will need a new model for system commands.
 - If smart is not enabled we should let the user know to enable it and how.
 - Cron should be configured to run at a regular interval of at least once every week.

Example:
```yaml
 - disks:
    - uuid: AISDYIAYSIDYUA
      options:
        - notification:
            enabled: true
        - log: true
    - uuid: BISDASDSAJFYUA
      options:
        - notification:
            enabled: true
        - log: true
```
Notify may be "true", "false" or "email" etc. Parsed as string. True will use server default.

Additionally we should allow the user to call the disk check directly.

## Steps to Reproduce the Problem

  1. ./server.bin -system disk-check
