### ISSUE TITLE
Startup IP Check

### ISSUE THREAD

**Issue by ldrrp** [SiloCityLabs/docker-nas#40]
## Problem

When the ip has changed and the server starts it tries to check against the old ip address in the config.yml not knowing it has changed.

## Solution

IP check on startup for ddns. If not correct we update it and notify user as this will likely fail ddns checks until it has propogated. This can be done by calling the existing ddns update function.

Configuration
```yaml
- ip-check:
    - notification:
            enabled: true
```

Notify may be "true", "false" or "email" etc. Parsed as string. True will use server default.

## Steps to Reproduce the Problem

  1. ./server.bin
