### ISSUE TITLE
Notify Package

### ISSUE THREAD

**Issue by ldrrp** [SiloCityLabs/docker-nas#43]
## Problem

No way to communicate with users other than logs.

## Solution

Create a package called notifications that wraps the package [notify](https://github.com/nikoksr/notify). This package will be used to send notifications. To user selected service or the default service. This should be written using an interface{} for the service configuration so that you can cast different structs for the service in question.

https://github.com/nikoksr/notify

```yaml
 - notifications:
    - notify: true
    - default: "telegram"
    - config:
      - name: telegram
        values: interface{}
```

Create a test action that will send a notification to the default service.

## Steps to Reproduce the Problem

  1. ./server.bin -test notify
