### ISSUE TITLE
Raid health check

### ISSUE THREAD

**Issue by ldrrp** [SiloCityLabs/docker-nas#47]
## Problem

Currently there are no checks for raid health. This is a problem if we want to ensure data is not lost.

## Solution

On a cron check for the health of the raids and if any are unhealthy we should notify the user and log the issue.

 - We must scan for all mdadm drives.
 - We should add those drives to a list of raids to configure in config.yml.
 - Include config.yml settings disk checks with a custom golang struct.
 - We will need a new model for system commands.

Example:
```yaml
 - raid:
    - uuid: AISDYIAYSIDYUA
      options:
        - notification:
            enabled: true
        - log: true
    - uuid: BISDASDSAJFYUA
      options:
        - notification:
            enabled: true
        - log: true
```

Notify may be "true", "false" or "email" etc. Parsed as string. True will use server default.

Additionally we should allow the user to call the raid check directly.

## Steps to Reproduce the Problem

  1. ./server.bin -system raid-check
