### ISSUE TITLE
Backup USB drive on insert

### ISSUE THREAD

**Issue by ldrrp** [SiloCityLabs/docker-nas#51]
## Problem

Want to backup flashdrives or external drives on insert withouth having to shell in, mount and move data around.

## Solution

- [ ] Using udev you can [watch for new drives](https://github.com/pilebones/go-udev/blob/master/main.go)
- [ ] When new drive is detected [check if its a usb drive](https://github.com/deepakjois/gousbdrivedetector)
- [ ] Mount the drive
- [ ] Create a backup directory in user specified location from config
- [ ] Copy the files over to the backup directory
- [ ] Unmount the drive
- [ ] Notify user of success if configured

Configuration
```yaml
- backups:
  - path: /docker-nas/home/backups
  - notification:
            enabled: true
```

Notify may be "true", "false" or "email" etc. Parsed as string. True will use server default.
